### PR TITLE
bye bye Alembic!

### PR DESCRIPTION
**Pull request by elthorne**

### CODE REVIEW

**Comment by jedimasterjonny** [comment]
A diffstat with a net minus is always good. A diff stat with minus 2,000 🤤🤤🤤

**Comment by anax32** [comment]
How is this being tested?

https://collaborate2.ons.gov.uk/confluence/display/QSS/Removal+of+redundant+Alembic+versions+from+blaise-survey-manager
indicates there are differences in the DB and documents change decisions, but all the python services use alembic models as well?

**Comment by elthorne** [comment]
Good question! (I've just seen this) I was wondering whether it was worth building this in a sandbox and testing those tables through the UI? Do you think that would be a sufficient test?

**Review by matthewandrewpalmer — APPROVED** [review]
:+1:

**Pull request merged**
