### PR TITLE
Stackdriver integration

### PR DESCRIPTION
**Pull request by pds2208**
Integrated google cloud loggin (stackdriver) alongside standard Python logging

### CODE REVIEW

**Review by anax32 — CHANGES_REQUESTED** [review]
this is not needed. Container stdout is captured by kubernetes and passed to stackdriver.

**Comment by pds2208** [comment]
> this is not needed. Container stdout is captured by kubernetes and passed to stackdriver.

My understanding is that the logging levels wasn't captured. this captured them

**Comment by pds2208** [comment]
image

**Review by anax32 — CHANGES_REQUESTED** [review]
this is will duplicate the existing logs. We log to stdout on the container which is captured by kubernetes and passed to stackdriver.

https://cloud.google.com/blog/products/management-tools/using-logging-your-apps-running-kubernetes-engine
the section is titled "Logging recommendations for containerized applications"

**Comment by anax32** [comment]
Do you want to go over how the logging setup works? The changes don't seem to have any effect?

**Pull request closed without merging**
